name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: artbreguez
        DOCKER_PASSWORD: C0necr#w123
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD --password-stdin 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag artbreguez/double-ai:latest
      
    - name: Docker Push
      run: docker push artbreguez/double-ai:latest
