name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: python:3.9.16-buster

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag <your-dockerhub-username>/double-ai:$(date +%s)
    - name: Push the Docker image to DockerHub
      run: docker push <your-dockerhub-username>/double-ai:$(date +%s)
