name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: artbreguez
          password: C0necr#w123
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2
      run: docker build . --tag artbreguez/double-ai:latest
    - name: Push the Docker image to DockerHub
      run: docker push artbreguez/double-ai:latest
