name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: artbreguez
        DOCKER_PASSWORD: C0necr#w123
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag artbreguez/double-ai:latest
      
    - name: Docker Push
      run: docker push artbreguez/double-ai:latest
